[package]
name = "dsb"
version = "0.1.0"
edition = "2024"

[dependencies]
array_chunks = "1.0.0"
atools = { git = "https://github.com/bend-n/atools", version = "0.1.7" }
fimg = { path = "../fimg", features = ["save", "real-show"] }
implicit-fn = "0.1.0"
itertools = "0.14.0"
lower = "0.2.0"
lru-cache = "0.1.2"
swash = "0.2.5"
swizzle = "0.1.0"
umath = "0.0.7"

[[test]]
name = "test"
harness = false
