[package]
name = "dsb"
version = "0.1.0"
edition = "2024"

[dependencies]
array_chunks = "1.0.0"
atools = { git = "https://git.bendn.org/atools", version = "0.1.7" }
car = "0.1.4"
fimg = { git = "https://git.bendn.org/fimg", features = ["save"] }
implicit-fn = "0.1.0"
itertools = "0.14.0"
lower = "0.2.1"
lru-cache = "0.1.2"
rangemap = "1.7.1"
serde = { version = "1.0.229", features = ["serde_derive"] }
swash = "0.2.10"
swizzle = "0.1.0"
umath = "0.0.7"

[[test]]
name = "test"
harness = false

[profile.release]
opt-level = 3
debug = true
